name: Monitor Abiraterone

on:
  schedule:
    - cron: "*/30 * * * *"  # кожні 30 хв
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # --- Кеш для state.txt, щоб бот пам’ятав останній стан ---
      - name: Cache state file
        uses: actions/cache@v3
        with:
          path: state.txt
          key: state-file-cache

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- Встановлення потрібних бібліотек ---
      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run monitor
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python parser.py
